export const GOLEM = {
	'cards': {
		'point': [
			{ 'gemsIn': 'gggg', 'pointsOut': 8 },
			{ 'gemsIn': 'ygtttm', 'pointsOut': 18 },
			{ 'gemsIn': 'yyggtt', 'pointsOut': 13 },
			{ 'gemsIn': 'ygggtm', 'pointsOut': 16 },
			{ 'gemsIn': 'gggtt', 'pointsOut': 12 },
			{ 'gemsIn': 'yyymm', 'pointsOut': 11 },
			{ 'gemsIn': 'yyggmm', 'pointsOut': 15 },
			{ 'gemsIn': 'ygtm', 'pointsOut': 12 },
			{ 'gemsIn': 'mmmmm', 'pointsOut': 20 },
			{ 'gemsIn': 'yyggg', 'pointsOut': 8 },
			{ 'gemsIn': 'tttt', 'pointsOut': 12 },
			{ 'gemsIn': 'yyttmm', 'pointsOut': 17 },
			{ 'gemsIn': 'yygm', 'pointsOut': 9 },
			{ 'gemsIn': 'mmmm', 'pointsOut': 16 },
			{ 'gemsIn': 'ttttt', 'pointsOut': 15 },
			{ 'gemsIn': 'yyttt', 'pointsOut': 11 },
			{ 'gemsIn': 'yygg', 'pointsOut': 6 },
			{ 'gemsIn': 'tttmm', 'pointsOut': 17 },
			{ 'gemsIn': 'yyybb', 'pointsOut': 9 },
			{ 'gemsIn': 'yymm', 'pointsOut': 10 },
			{ 'gemsIn': 'ggmm', 'pointsOut': 12 },
			{ 'gemsIn': 'ygtmmm', 'pointsOut': 20 },
			{ 'gemsIn': 'yymmm', 'pointsOut': 14 },
			{ 'gemsIn': 'yytt', 'pointsOut': 8 },
			{ 'gemsIn': 'gggmm', 'pointsOut': 14 },
			{ 'gemsIn': 'ggggg', 'pointsOut': 10 },
			{ 'gemsIn': 'ggtt', 'pointsOut': 10 },
			{ 'gemsIn': 'yyygtm', 'pointsOut': 14 },
			{ 'gemsIn': 'yttm', 'pointsOut': 12 },
			{ 'gemsIn': 'ggttt', 'pointsOut': 13 },
			{ 'gemsIn': 'ggtm', 'pointsOut': 12 },
			{ 'gemsIn': 'ggttmm', 'pointsOut': 19 },
			{ 'gemsIn': 'ggmmm', 'pointsOut': 16 },
			{ 'gemsIn': 'ttmmm', 'pointsOut': 18 },
			{ 'gemsIn': 'yyygg', 'pointsOut': 7 },
			{ 'gemsIn': 'ttmm', 'pointsOut': 14 }
		],
		'merchant': {
			'starting': [
				{ 'gemsIn': 2, 'gemsOut': '++' },
				{ 'gemsOut': 'yy' }
			],
			'nonStarting': {
				'multiplesAllowed': [
					{ 'gemsIn': 'mm', 'gemsOut': 'gggtt' },
					{ 'gemsIn': 'tt', 'gemsOut': 'ggm' },
					{ 'gemsIn': 'm', 'gemsOut': 'yyyt' },
					{ 'gemsIn': 'gg', 'gemsOut': 'yym' },
					{ 'gemsIn': 't', 'gemsOut': 'ygg' },
					{ 'gemsIn': 'gg', 'gemsOut': 'yyyt' },
					{ 'gemsIn': 'ggg', 'gemsOut': 'yytt' },
					{ 'gemsIn': 'tyy', 'gemsOut': 'mm' },
					{ 'gemsIn': 'yyyy', 'gemsOut': 'tm' },
					{ 'gemsIn': 'tt', 'gemsOut': 'yyggg' },
					{ 'gemsIn': 'ttt', 'gemsOut': 'mmm' },
					{ 'gemsIn': 'yy', 'gemsOut': 'gg' },
					{ 'gemsIn': 'yyyy', 'gemsOut': 'tt' },
					{ 'gemsIn': 'tt', 'gemsOut': 'yygm' },
					{ 'gemsIn': 'ggg', 'gemsOut': 'ytm' },
					{ 'gemsIn': 'yy', 'gemsOut': 't' },
					{ 'gemsIn': 'g', 'gemsOut': 'yyy' },
					{ 'gemsIn': 't', 'gemsOut': 'yyyyg' },
					{ 'gemsIn': 'yyyyy', 'gemsOut': 'mm' },
					{ 'gemsIn': 'm', 'gemsOut': 'ygt' },
					{ 'gemsIn': 'm', 'gemsOut': 'tt' },
					{ 'gemsIn': 'yg', 'gemsOut': 'm' },
					{ 'gemsIn': 'm', 'gemsOut': 'ggg' },
					{ 'gemsIn': 'yyy', 'gemsOut': 'gt' },
					{ 'gemsIn': 'yyy', 'gemsOut': 'm' },
					{ 'gemsIn': 'm', 'gemsOut': 'yygg' },
					{ 'gemsIn': 'gg', 'gemsOut': 'tt' },
					{ 'gemsIn': 'mm', 'gemsOut': 'ygttt' },
					{ 'gemsIn': 'ggg', 'gemsOut': 'mm' },
					{ 'gemsIn': 'ggg', 'gemsOut': 'ttt' },
					{ 'gemsIn': 'yyy', 'gemsOut': 'ggg' },
					{ 'gemsIn': 't', 'gemsOut': 'gg' },
					{ 'gemsIn': 'tt', 'gemsOut': 'mm' },
					{ 'gemsIn': 'yyyyy', 'gemsOut': 'ttt' }
				],
				'multiplesNotAllowed': [
					{ 'gemsOut': 'm' },
					{ 'gemsOut': 'yyyy' },
					{ 'gemsOut': 't' },
					{ 'gemsOut': 'yyg' },
					{ 'gemsOut': 'yyy' },
					{ 'gemsOut': 'yg' },
					{ 'gemsOut': 'yt' },
					{ 'gemsOut': 'gg' },
					{ 'gemsIn': 3, 'gemsOut': '+++' }
				]
			}
		}
	},
	'coins': [ 'copper', 'silver' ],
	'numCoinsEach': 10,
	'gems': [ 'yellow', 'green', 'turquoise', 'magenta' ],
	'numGemsEach': 20,
	'numPlayersAllowed': 5
};
